version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Starting the React build process..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Contents of the build folder:"
      - ls -la build/

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
