version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cd reactapp  # Change to the directory where package.json is located
      - npm install  # Install dependencies from reactapp/package.json

  build:
    commands:
      - echo "Building the application"
      - cd reactapp  # Ensure we're still in the reactapp directory
      - npm run build

artifacts:
  base-directory: reactapp/src  # Adjust to the correct build output directory
  files:
    - '**/*'
