version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cd cakefend/reactapp  # Adjust this path as necessary
      - npm install

  build:
    commands:
      - echo "Building the application"
      - cd cakefend/reactapp
      - npm run build

artifacts:
  base-directory: cakefend/reactapp/src  # Adjust this path too
  files:
    - '**/*'
