version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install  # Install dependencies from package.json
  
  build:
    commands:
      - echo "Building the application"
      - npm run build  # Build the frontend project (e.g., React app)
      - echo "Build complete"
  
artifacts:
  base-directory: build  # The directory where the build output is located (adjust this if needed)
  files:
    - '**/*'  # All files in the build directory
  discard-paths: no  # Keep the directory structure when uploading to S3
