version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the application"
      - npm run build --prefix reactapp

artifacts:
  base-directory: reactapp/dist
  files:
    - '**/*'
