version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build --prod  # Build the Angular app for production

artifacts:
  files:
    - '**/*'  # Include all files in the output
  discard-paths: no
  base-directory: dist/your-app-name  # Replace 'your-app-name' with your Angular app's folder name inside 'dist'
